---
actions:
  to: skaffold.yaml
---
apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: {{artifactId}}
build:
  artifacts:
  - image: {{artifactId}}
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml
portForward:
  - resourceType: service
    resourceName: {{artifactId}}-service
    port: 80
    localPort: 8080
